language: node_js
node_js:
- '6'
before_install:
# TODO OSS
# - npm i npm-cli-login -g
# - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
# - npm who
- echo "registry = https://realglobe.artifactoryonline.com/realglobe/api/npm/npm-virtual" > $HOME/.npmrc
- curl -u${NPM_USER}:${NPM_PASSWORD} "https://realglobe.artifactoryonline.com/realglobe/api/npm/auth" >> $HOME/.npmrc
- cat $HOME/.npmrc
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
# - ./ci/doc.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "kBe5yor06NaYHPRVjW2q8hUAc4/0z5S+ohdwR/X5t/E7c0Tcls9xJMYrb9epGwhizYbRW6wrdtOPMTY7uHSXIt30SS6ytdXVkl4GbDObeZvHf8qw0k7eXa6Pd/PdA1/m4IyCl/n2+sxxqkxh65ZNLtxCS+AOyKxBwixWQTrcK09IfTG129lld6DFwSRizvZsSUmtdtWVtVjfl0RGZLyqgJbfkfE/tu2Yi5H2JkFkzQef/QcPM7WZuXf4DB1i4vztK+Jjb9wWyTbxfujzDaQo8jt0ecfJ/gPP30p3jL3DBh1siSG5seSHpbcKLgiLAFHqF2DICfJYrDEuPtpbwob3eBZoaNBjL2OFZGEd/QGdyrCLUOrQSuJRlySE+SIyGUPBWxB4MR0wEd2N15FebilQRaq/4B73wd7P1nD4z1shU/f+CbI++jYhTnlue5w5JIF6iQ1W80++IW5BRd4CxdX/D9JV6c3mUnP+e+zop0fma0kuFtQTzeDPJ1LUPo1Kuici0TStead7+Pmjs+jAvJtdlPr7a+ig1+k3eejpFXzHveSfi4gIEju+A8VHaS2u6N4K3AfFJLd+B3JosHpf1Yy9vMg3Q44DWBOhCP+gmQDn0FaZeu+M2NFO+8hg+CdZEEf7V+d7YeCyBCy2SK4WXNAizqDbEM31gEQxy5AJoOR6d1w="
