language: node_js
node_js:
- '8'
before_install:
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
- npm install jsdoc publish-if-needed npm@latest -g
install:
- npm install
script:
- "./ci/build.js"
- "./ci/shim.js"
- "./ci/test.js"
after_success:
- publish-if-needed
env:
  global:
  - secure: ghs6kNJZ1KRZrMDk3ErXyEY+wask99pX6FaltSHvutG6DBVnf3+4XvX9eVY8oQCKNnWMaw/sTeBbHS5yL3w9/p0IasHzm85sW8ZuIZGPlvrjmitk/p5KvPTWCR27aJuZMKiPomiLgHu/TYQgXOJN/u8LXfRPJu/N6zeKe9oeJ3dpyirHdk9C+HlMx/SAw/UZrnbHPVKrGptWG3edWV9lNY21K/8XLynYXqRNYwE/ClNXx+uUptPGAcAvfkeYeSCom30AY5HYrB2ZgYFV9C1A2xcTgO4W1eQEOob/XvmuRXc8+qYgncoXfyPxxJrbNT3GMzsN6EMigBJRB65Vnl8AzVpLjTZOgLGfjEIpqzAS7swuJpEkpAV1ZoujXQE3VH0Pa+HI1QLt4Il3zJAYFXKmEWffl6PUX2yQgI2SJDESfIZTXNQ07G9PNqi4dVKsZ51LSWVgcu/viU2ja0JhZ55iVYiTHeHHu3u8xehVR/KsQAHHAQmU8lj4IQ0jthCNJJhVDT0AH9XEDZ7BwEgVlq8O1Vk26SS0/uTxBgolCwBvuRy26vRJ9nd0yC5jYA06AVobGlgVvHfzDGlVKsoxYwH1d6aGPjp53Qo+PmqNtGtgmoLf/boDxEmEqyWMc77renHgiFE17OBl+lsEZJGQNIof/QS/XZkgwfVQEGyyNCo7HfY=
  - secure: K4D+fxojCINm2DRt9wLcOsi55R7kdFyhmGZFAbFR7+5tQlWveITitovzEb4jN2lSLcOCWfQhingPo1UeyI5WeIazdRxCOKFt3o2DjXem3QIfRHTzBkZV7a6vEQh5bS/NmKU5YUEjF5DYVLk1fp4BUECG1PmjspVmwzXLS0ebmj51eVR+0gW8ezOPZCL2i0ia5RgLu1JGQ05Bdjj5sQ1Xz333UCUvlbeGee4x7CDTPBc1y0szGuiULz7+kPvdzLEZr1MGd95UEdnmCIZNOqKOH+e59htB7psMEVvu3wozcGL9AS1hU9vAPFk+BBLlFuheSZBxixXMm0QYsp/SEs4sIDCtBO39a3XvGjHRLFo8iNSufHCV3CttB9NnHC6E/J660jQJtbH8tHevKMFbg9dV4ad8VnYPy1/JxUcDuUQNBINjP8fqImg1H9qo673wfdEX4zgSxWz1m4jVWOCK86kJj7N/XpT/6GxLMIzu5iyX7m8kR41DJSyV0NBMZusFC7zn/xVt+pP99UtiS4NBNF1RWiHzQaJus0LsQkXTq7m2tgQz7+6sMOTVWDcA3xi3eqqRUKB+hoDq/lelHsY6lV4DHVyyWbKvW12HLeP84jDlcpAHphracL6kmfAfyuYpZuzVJb9tu01vdSdrU6ZH8SvYxi64hg/DbpqBjnqt5TRL/A4=
