language: node_js
node_js:
- '6'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "MofC5+MkBo/ExTJ0pmGwNNMIz04fhsXTEoSZWhkyE1iMKHB/Vchlzg0cWfpSDHmyqnH6wjr5CLiiUqXGdMU0ZIXJfWSHxAEjRY7lQ0mv9WZLSOfG9nDHG3gaAsbJusizxSMC0nifPVltyxdE3FAsYXO2GPG//wgl7ueFhY+1mESRrC71MNzpAH4DHC33FE6DHkcPNBIVEBvg97fW+Mzt++11XZhHqB5Fk+TZjMM63rQa5Pt6UUq3FQTkdOUSE5k+Jl71SfW4WqYLK9rbGvBB3LhwOW2qC8c0cSuDXsuZSd7JRPJe8s8Z2iLdHd9VTKu54poiIIzaz6PzgI2E6TS9BvQX/9lnorC8mbX405/DeE4hGiRGIfaVl1H4qBcQr9HXKle9W0g48M5d4pLV1+LhiQbNBx/uRTFl/WO3MHCkpfcX/Q5RhL+CP/93cRP25kQqfm1WccoNbzUzHlArhqK9ELPFJtjlQQd90B00+uRVW7gxsN9zhsWldtJU939zGDJYuR3I4fTSOBDbpTSuDRrCydWu+y8HNx4kCgV0FP0DSwdG6hzNPNQP3pJypkOiU8pURuHTaPfDqf+Ty7V4OMQ2mFeHWgEiqYNC2h7r8ypUX3ok7EndiDkIztDJxop+GqcJKXr2zc6+fbjGSPHNjtEBXDMOnJlZSPYWCCu199+LFjI="
