language: node_js
node_js:
- '8'
before_install:
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
- npm install jsdoc publish-if-needed npm@latest -g
install:
- npm install
script:
- "./ci/build.js"
- "./ci/shim.js"
- "./ci/test.js"
after_success:
- publish-if-needed
env:
  global:
  - secure: ghs6kNJZ1KRZrMDk3ErXyEY+wask99pX6FaltSHvutG6DBVnf3+4XvX9eVY8oQCKNnWMaw/sTeBbHS5yL3w9/p0IasHzm85sW8ZuIZGPlvrjmitk/p5KvPTWCR27aJuZMKiPomiLgHu/TYQgXOJN/u8LXfRPJu/N6zeKe9oeJ3dpyirHdk9C+HlMx/SAw/UZrnbHPVKrGptWG3edWV9lNY21K/8XLynYXqRNYwE/ClNXx+uUptPGAcAvfkeYeSCom30AY5HYrB2ZgYFV9C1A2xcTgO4W1eQEOob/XvmuRXc8+qYgncoXfyPxxJrbNT3GMzsN6EMigBJRB65Vnl8AzVpLjTZOgLGfjEIpqzAS7swuJpEkpAV1ZoujXQE3VH0Pa+HI1QLt4Il3zJAYFXKmEWffl6PUX2yQgI2SJDESfIZTXNQ07G9PNqi4dVKsZ51LSWVgcu/viU2ja0JhZ55iVYiTHeHHu3u8xehVR/KsQAHHAQmU8lj4IQ0jthCNJJhVDT0AH9XEDZ7BwEgVlq8O1Vk26SS0/uTxBgolCwBvuRy26vRJ9nd0yC5jYA06AVobGlgVvHfzDGlVKsoxYwH1d6aGPjp53Qo+PmqNtGtgmoLf/boDxEmEqyWMc77renHgiFE17OBl+lsEZJGQNIof/QS/XZkgwfVQEGyyNCo7HfY=
